services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - database

  database:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}                   #here directly the userid and pass of the Database Show So We di same as groq api -> put to the env file
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: